#!/usr/bin/expect

set hordefilesystem [lindex $argv 0]


spawn pear run-scripts horde/horde_role


while {1} {
    expect {
        -re {Filesystem location .*}            {send $hordefilesystem\r}
        eof                                     {break}
    }
}
