#!/usr/bin/expect

set mysqlpassword [lindex $argv 0]
set databasename [lindex $argv 1]
set country [lindex $argv 2]
set state [lindex $argv 3]
set city [lindex $argv 4]
set organization [lindex $argv 5]
set unit [lindex $argv 6]
set commonname [lindex $argv 7]
set email [lindex $argv 8]
set port [lindex $argv 9]
set ssl [lindex $argv 10]
set country [lindex $argv 11]
set state [lindex $argv 12]
set city [lindex $argv 13]
set organization [lindex $argv 14]
set unit [lindex $argv 15]
set email [lindex $argv 16]


spawn php -q /tmp/ispconfig3_install/install/install.php


while {1} {
    expect {
        -re {Select language .*\[.*\]:}          {send \r}
        -re {Installation mode .*\[.*\]:}        {send \r}
        -re {Full qualified hostname .*\[.*\]:}  {send \r}
        -re {MySQL server hostname .*\[.*\]:}    {send \r}
        -re {MySQL root username .*\[.*\]:}      {send \r}
        -re {MySQL root password .*\[.*\]:}      {send $mysqlpassword\r}
        -re {MySQL database .*\[.*\]:}           {send $databasename\r}
        -re {MySQL charset .*\[.*\]:}            {send \r}
        -re {Country Name .*\[.*\]:}             {send $country\r}
        -re {State or Province .*\[.*\]:}        {send $state\r}
        -re {Locality Name .*\[.*\]:}            {send $city\r}
        -re {Organization Name .*\[.*\]:}        {send $organization\r}
        -re {Organizational Unit .*\[.*\]:}      {send $unit\r}
        -re {Common Name .*\[.*\]:}              {send $commonname\r}
        -re {Email Address .*\[.*\]:}            {send $email\r}
        -re {ISPConfig Port .*\[.*\]:}           {send $port\r}
        -re {Do you want a secure .*\[.*\]:}     {send $ssl\r}
        -re {A challenge password .*\[.*\]:}     {send \r}
        -re {An optional company .*\[.*\]:} {send \r}
        eof                                      {break}
    }
}
