#!/usr/bin/expect

set mysqlpassword [lindex $argv 0]
set hordedatabase [lindex $argv 1]
set hordeuser [lindex $argv 2]
set hordepassword [lindex $argv 3]


spawn mysql -u root -p


while {1} {
    expect {
        -re {Enter password .*\[.*\]:}           {send $mysqlpassword\r}
        -re {mysql> .*\[.*\]:}                   {send CREATE DATABASE ${hordedatabase}; GRANT ALL ON ${hordedatabase}.* TO ${hordeuser}@localhost IDENTIFIED BY '${hordepassword}'; FLUSH PRIVILEGES; exit;\r}
        eof                                      {break}
    }
}
