#!/usr/bin/expect

set mysqlpassword [lindex $argv 0]

spawn mysql_secure_installation


while {1} {
    expect {
        -re {Enter current password .*}          {send $mysqlpassword\r}
        -re {Change the root .*\[.*\]?}          {send n\r}
        -re {Remove anonymous .*\[.*\]?}         {send y\r}
        -re {Disallow root login .*\[.*\]?}      {send y\r}
        -re {Remove test database .*\[.*\]?}     {send y\r}
        -re {Reload privilege tables .*\[.*\]?}  {send y\r}
        eof                                      {break}
    }
}
